name: Build and Publish Docker Image

# Triggers workflow on push to main branch
on:
  push:
    branches: [main]

# Define jobs to be executed
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using the secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Extract metadata (tags, labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/dev-agora-fe # Replace 'your-repo-name'
          tags: |
            type=ref,event=branch
            type=sha,prefix=,suffix=,format=short

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the root of the repository
          push: true # Push the image after building
          tags: |
            ${{ steps.meta.outputs.tags }},
            ${{ vars.DOCKERHUB_USERNAME }}/my-portfolio:latest
          labels: ${{ steps.meta.outputs.labels }} # Labels from the meta step
          
